/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WizardRouteImport } from './routes/wizard'
import { Route as ShareRouteImport } from './routes/share'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PromptsImportRouteImport } from './routes/prompts/import'
import { Route as PromptsSlugRouteImport } from './routes/prompts/$slug'
import { Route as LlmsTxtRouteImport } from './routes/llms.txt'
import { Route as ApiSentryExampleRouteImport } from './routes/api/sentry-example'
import { Route as ApiSentryTunnelRouteImport } from './routes/api/sentry.tunnel'
import { Route as ApiAiGenerateRouteImport } from './routes/api/ai/generate'

const WizardRoute = WizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsImportRoute = PromptsImportRouteImport.update({
  id: '/prompts/import',
  path: '/prompts/import',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsSlugRoute = PromptsSlugRouteImport.update({
  id: '/prompts/$slug',
  path: '/prompts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsTxtRoute = LlmsTxtRouteImport.update({
  id: '/llms/txt',
  path: '/llms/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSentryExampleRoute = ApiSentryExampleRouteImport.update({
  id: '/api/sentry-example',
  path: '/api/sentry-example',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSentryTunnelRoute = ApiSentryTunnelRouteImport.update({
  id: '/api/sentry/tunnel',
  path: '/api/sentry/tunnel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateRoute = ApiAiGenerateRouteImport.update({
  id: '/api/ai/generate',
  path: '/api/ai/generate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/share': typeof ShareRoute
  '/wizard': typeof WizardRoute
  '/api/sentry-example': typeof ApiSentryExampleRoute
  '/llms/txt': typeof LlmsTxtRoute
  '/prompts/$slug': typeof PromptsSlugRoute
  '/prompts/import': typeof PromptsImportRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/sentry/tunnel': typeof ApiSentryTunnelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/share': typeof ShareRoute
  '/wizard': typeof WizardRoute
  '/api/sentry-example': typeof ApiSentryExampleRoute
  '/llms/txt': typeof LlmsTxtRoute
  '/prompts/$slug': typeof PromptsSlugRoute
  '/prompts/import': typeof PromptsImportRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/sentry/tunnel': typeof ApiSentryTunnelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/share': typeof ShareRoute
  '/wizard': typeof WizardRoute
  '/api/sentry-example': typeof ApiSentryExampleRoute
  '/llms/txt': typeof LlmsTxtRoute
  '/prompts/$slug': typeof PromptsSlugRoute
  '/prompts/import': typeof PromptsImportRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/sentry/tunnel': typeof ApiSentryTunnelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/share'
    | '/wizard'
    | '/api/sentry-example'
    | '/llms/txt'
    | '/prompts/$slug'
    | '/prompts/import'
    | '/api/ai/generate'
    | '/api/sentry/tunnel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/share'
    | '/wizard'
    | '/api/sentry-example'
    | '/llms/txt'
    | '/prompts/$slug'
    | '/prompts/import'
    | '/api/ai/generate'
    | '/api/sentry/tunnel'
  id:
    | '__root__'
    | '/'
    | '/share'
    | '/wizard'
    | '/api/sentry-example'
    | '/llms/txt'
    | '/prompts/$slug'
    | '/prompts/import'
    | '/api/ai/generate'
    | '/api/sentry/tunnel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShareRoute: typeof ShareRoute
  WizardRoute: typeof WizardRoute
  ApiSentryExampleRoute: typeof ApiSentryExampleRoute
  LlmsTxtRoute: typeof LlmsTxtRoute
  PromptsSlugRoute: typeof PromptsSlugRoute
  PromptsImportRoute: typeof PromptsImportRoute
  ApiAiGenerateRoute: typeof ApiAiGenerateRoute
  ApiSentryTunnelRoute: typeof ApiSentryTunnelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wizard': {
      id: '/wizard'
      path: '/wizard'
      fullPath: '/wizard'
      preLoaderRoute: typeof WizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts/import': {
      id: '/prompts/import'
      path: '/prompts/import'
      fullPath: '/prompts/import'
      preLoaderRoute: typeof PromptsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts/$slug': {
      id: '/prompts/$slug'
      path: '/prompts/$slug'
      fullPath: '/prompts/$slug'
      preLoaderRoute: typeof PromptsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms/txt': {
      id: '/llms/txt'
      path: '/llms/txt'
      fullPath: '/llms/txt'
      preLoaderRoute: typeof LlmsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sentry-example': {
      id: '/api/sentry-example'
      path: '/api/sentry-example'
      fullPath: '/api/sentry-example'
      preLoaderRoute: typeof ApiSentryExampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sentry/tunnel': {
      id: '/api/sentry/tunnel'
      path: '/api/sentry/tunnel'
      fullPath: '/api/sentry/tunnel'
      preLoaderRoute: typeof ApiSentryTunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate': {
      id: '/api/ai/generate'
      path: '/api/ai/generate'
      fullPath: '/api/ai/generate'
      preLoaderRoute: typeof ApiAiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShareRoute: ShareRoute,
  WizardRoute: WizardRoute,
  ApiSentryExampleRoute: ApiSentryExampleRoute,
  LlmsTxtRoute: LlmsTxtRoute,
  PromptsSlugRoute: PromptsSlugRoute,
  PromptsImportRoute: PromptsImportRoute,
  ApiAiGenerateRoute: ApiAiGenerateRoute,
  ApiSentryTunnelRoute: ApiSentryTunnelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
