/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PromptBuilderAdvancedRouteImport } from './routes/prompt-builder/advanced'
import { Route as _demoStartServerFuncsRouteImport } from './routes/__demo/start.server-funcs'
import { Route as _demoStartApiRequestRouteImport } from './routes/__demo/start.api-request'
import { Route as _demoFormSimpleRouteImport } from './routes/__demo/form.simple'
import { Route as _demoFormAddressRouteImport } from './routes/__demo/form.address'
import { Route as _demoApiNamesRouteImport } from './routes/__demo/api.names'
import { Route as _demoStartSsrIndexRouteImport } from './routes/__demo/start.ssr.index'
import { Route as _demoStartSsrSpaModeRouteImport } from './routes/__demo/start.ssr.spa-mode'
import { Route as _demoStartSsrFullSsrRouteImport } from './routes/__demo/start.ssr.full-ssr'
import { Route as _demoStartSsrDataOnlyRouteImport } from './routes/__demo/start.ssr.data-only'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptBuilderAdvancedRoute = PromptBuilderAdvancedRouteImport.update({
  id: '/prompt-builder/advanced',
  path: '/prompt-builder/advanced',
  getParentRoute: () => rootRouteImport,
} as any)
const _demoStartServerFuncsRoute = _demoStartServerFuncsRouteImport.update({
  id: '/__demo/start/server-funcs',
  path: '/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const _demoStartApiRequestRoute = _demoStartApiRequestRouteImport.update({
  id: '/__demo/start/api-request',
  path: '/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const _demoFormSimpleRoute = _demoFormSimpleRouteImport.update({
  id: '/__demo/form/simple',
  path: '/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const _demoFormAddressRoute = _demoFormAddressRouteImport.update({
  id: '/__demo/form/address',
  path: '/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const _demoApiNamesRoute = _demoApiNamesRouteImport.update({
  id: '/__demo/api/names',
  path: '/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const _demoStartSsrIndexRoute = _demoStartSsrIndexRouteImport.update({
  id: '/__demo/start/ssr/',
  path: '/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const _demoStartSsrSpaModeRoute = _demoStartSsrSpaModeRouteImport.update({
  id: '/__demo/start/ssr/spa-mode',
  path: '/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const _demoStartSsrFullSsrRoute = _demoStartSsrFullSsrRouteImport.update({
  id: '/__demo/start/ssr/full-ssr',
  path: '/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const _demoStartSsrDataOnlyRoute = _demoStartSsrDataOnlyRouteImport.update({
  id: '/__demo/start/ssr/data-only',
  path: '/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prompt-builder/advanced': typeof PromptBuilderAdvancedRoute
  '/api/names': typeof _demoApiNamesRoute
  '/form/address': typeof _demoFormAddressRoute
  '/form/simple': typeof _demoFormSimpleRoute
  '/start/api-request': typeof _demoStartApiRequestRoute
  '/start/server-funcs': typeof _demoStartServerFuncsRoute
  '/start/ssr/data-only': typeof _demoStartSsrDataOnlyRoute
  '/start/ssr/full-ssr': typeof _demoStartSsrFullSsrRoute
  '/start/ssr/spa-mode': typeof _demoStartSsrSpaModeRoute
  '/start/ssr': typeof _demoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prompt-builder/advanced': typeof PromptBuilderAdvancedRoute
  '/api/names': typeof _demoApiNamesRoute
  '/form/address': typeof _demoFormAddressRoute
  '/form/simple': typeof _demoFormSimpleRoute
  '/start/api-request': typeof _demoStartApiRequestRoute
  '/start/server-funcs': typeof _demoStartServerFuncsRoute
  '/start/ssr/data-only': typeof _demoStartSsrDataOnlyRoute
  '/start/ssr/full-ssr': typeof _demoStartSsrFullSsrRoute
  '/start/ssr/spa-mode': typeof _demoStartSsrSpaModeRoute
  '/start/ssr': typeof _demoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prompt-builder/advanced': typeof PromptBuilderAdvancedRoute
  '/__demo/api/names': typeof _demoApiNamesRoute
  '/__demo/form/address': typeof _demoFormAddressRoute
  '/__demo/form/simple': typeof _demoFormSimpleRoute
  '/__demo/start/api-request': typeof _demoStartApiRequestRoute
  '/__demo/start/server-funcs': typeof _demoStartServerFuncsRoute
  '/__demo/start/ssr/data-only': typeof _demoStartSsrDataOnlyRoute
  '/__demo/start/ssr/full-ssr': typeof _demoStartSsrFullSsrRoute
  '/__demo/start/ssr/spa-mode': typeof _demoStartSsrSpaModeRoute
  '/__demo/start/ssr/': typeof _demoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/prompt-builder/advanced'
    | '/api/names'
    | '/form/address'
    | '/form/simple'
    | '/start/api-request'
    | '/start/server-funcs'
    | '/start/ssr/data-only'
    | '/start/ssr/full-ssr'
    | '/start/ssr/spa-mode'
    | '/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/prompt-builder/advanced'
    | '/api/names'
    | '/form/address'
    | '/form/simple'
    | '/start/api-request'
    | '/start/server-funcs'
    | '/start/ssr/data-only'
    | '/start/ssr/full-ssr'
    | '/start/ssr/spa-mode'
    | '/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/prompt-builder/advanced'
    | '/__demo/api/names'
    | '/__demo/form/address'
    | '/__demo/form/simple'
    | '/__demo/start/api-request'
    | '/__demo/start/server-funcs'
    | '/__demo/start/ssr/data-only'
    | '/__demo/start/ssr/full-ssr'
    | '/__demo/start/ssr/spa-mode'
    | '/__demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PromptBuilderAdvancedRoute: typeof PromptBuilderAdvancedRoute
  _demoApiNamesRoute: typeof _demoApiNamesRoute
  _demoFormAddressRoute: typeof _demoFormAddressRoute
  _demoFormSimpleRoute: typeof _demoFormSimpleRoute
  _demoStartApiRequestRoute: typeof _demoStartApiRequestRoute
  _demoStartServerFuncsRoute: typeof _demoStartServerFuncsRoute
  _demoStartSsrDataOnlyRoute: typeof _demoStartSsrDataOnlyRoute
  _demoStartSsrFullSsrRoute: typeof _demoStartSsrFullSsrRoute
  _demoStartSsrSpaModeRoute: typeof _demoStartSsrSpaModeRoute
  _demoStartSsrIndexRoute: typeof _demoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt-builder/advanced': {
      id: '/prompt-builder/advanced'
      path: '/prompt-builder/advanced'
      fullPath: '/prompt-builder/advanced'
      preLoaderRoute: typeof PromptBuilderAdvancedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__demo/start/server-funcs': {
      id: '/__demo/start/server-funcs'
      path: '/start/server-funcs'
      fullPath: '/start/server-funcs'
      preLoaderRoute: typeof _demoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__demo/start/api-request': {
      id: '/__demo/start/api-request'
      path: '/start/api-request'
      fullPath: '/start/api-request'
      preLoaderRoute: typeof _demoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__demo/form/simple': {
      id: '/__demo/form/simple'
      path: '/form/simple'
      fullPath: '/form/simple'
      preLoaderRoute: typeof _demoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__demo/form/address': {
      id: '/__demo/form/address'
      path: '/form/address'
      fullPath: '/form/address'
      preLoaderRoute: typeof _demoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__demo/api/names': {
      id: '/__demo/api/names'
      path: '/api/names'
      fullPath: '/api/names'
      preLoaderRoute: typeof _demoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__demo/start/ssr/': {
      id: '/__demo/start/ssr/'
      path: '/start/ssr'
      fullPath: '/start/ssr'
      preLoaderRoute: typeof _demoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__demo/start/ssr/spa-mode': {
      id: '/__demo/start/ssr/spa-mode'
      path: '/start/ssr/spa-mode'
      fullPath: '/start/ssr/spa-mode'
      preLoaderRoute: typeof _demoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__demo/start/ssr/full-ssr': {
      id: '/__demo/start/ssr/full-ssr'
      path: '/start/ssr/full-ssr'
      fullPath: '/start/ssr/full-ssr'
      preLoaderRoute: typeof _demoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__demo/start/ssr/data-only': {
      id: '/__demo/start/ssr/data-only'
      path: '/start/ssr/data-only'
      fullPath: '/start/ssr/data-only'
      preLoaderRoute: typeof _demoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PromptBuilderAdvancedRoute: PromptBuilderAdvancedRoute,
  _demoApiNamesRoute: _demoApiNamesRoute,
  _demoFormAddressRoute: _demoFormAddressRoute,
  _demoFormSimpleRoute: _demoFormSimpleRoute,
  _demoStartApiRequestRoute: _demoStartApiRequestRoute,
  _demoStartServerFuncsRoute: _demoStartServerFuncsRoute,
  _demoStartSsrDataOnlyRoute: _demoStartSsrDataOnlyRoute,
  _demoStartSsrFullSsrRoute: _demoStartSsrFullSsrRoute,
  _demoStartSsrSpaModeRoute: _demoStartSsrSpaModeRoute,
  _demoStartSsrIndexRoute: _demoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
